/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Botanist;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Interface.Employee.EmployeeAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class BotanistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel CardPanel;
    private UserAccount account;

    /**
     * Creates new form BotanistWorkAreaJPanel
     */
    public BotanistWorkAreaJPanel(JPanel a, UserAccount b) {
        initComponents();
        this.CardPanel = a;
        this.account = b;
        this.setBackground(null);
        this.setOpaque(false);
        this.setBackground(null);
        this.setOpaque(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkWorkScheduleBtn = new javax.swing.JButton();
        myAccBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Botanist Work Area");

        checkWorkScheduleBtn.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        checkWorkScheduleBtn.setText("My Work Schedule");
        checkWorkScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWorkScheduleBtnActionPerformed(evt);
            }
        });

        myAccBtn.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        myAccBtn.setText("My Account");
        myAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(234, 234, 234)
                            .addComponent(checkWorkScheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(checkWorkScheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccBtnActionPerformed
        // TODO add your handling code here:
        EmployeeAccountJPanel eajp = new EmployeeAccountJPanel(CardPanel, account);
        CardPanel.add("EmployeeAccountJPanel", eajp);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);

    }//GEN-LAST:event_myAccBtnActionPerformed

    private void checkWorkScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWorkScheduleBtnActionPerformed
        // TODO add your handling code here:
        BotanistWorkSchedule eajp = new BotanistWorkSchedule(CardPanel, account);
        CardPanel.add("BotanistWorkSchedule", eajp);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_checkWorkScheduleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkWorkScheduleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton myAccBtn;
    // End of variables declaration//GEN-END:variables
}
