/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Botanist;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.AnimalReportRequest;
import Business.WorkQueue.PlantReportRequest;
import Interface.Employee.EmployeeAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YueZheng
 */
public class BotanistWorkSchedule extends javax.swing.JPanel {

    private JPanel CardPanel;
    private UserAccount account;

    /**
     * Creates new form BotanistWorkSchedule
     */
    public BotanistWorkSchedule(JPanel a, UserAccount b) {
        this.CardPanel = a;
        this.account = b;
        initComponents();
        populateTable();
        this.setBackground(null);
        this.setOpaque(false);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) PlantReportTable.getModel();
        model.setRowCount(0);
        for (PlantReportRequest request : account.getWorkQueue().getPlantReportRequestList()) {
            Object[] row = new Object[2];
            row[0] = request;
            row[1] = request.getReport().getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlantReportTable = new javax.swing.JTable();
        processBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Botanist Work Schedule");

        PlantReportTable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        PlantReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plant", "Status"
            }
        ));
        PlantReportTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(PlantReportTable);

        processBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(279, 279, 279)
                            .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = PlantReportTable.getSelectedRow();
        if (selectedRow >= 0) {
            PlantReportRequest a = (PlantReportRequest) PlantReportTable.getValueAt(selectedRow, 0);
            if(a.getReport().getStatus().equalsIgnoreCase("Checked")){
                JOptionPane.showMessageDialog(null, "Already Checked");
            }
            else{
            WritePlantReportJPanel evsjp = new WritePlantReportJPanel(CardPanel, a);
            CardPanel.add("EnterVitalSignsJPanel", evsjp);
            CardLayout layout = (CardLayout) CardPanel.getLayout();
            layout.next(CardPanel);

        } }else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_processBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);

    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PlantReportTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
