/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Botanist;

import Interface.Employee.Botanist.BotanistWorkSchedule;
import Business.WorkQueue.PlantReportRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class WritePlantReportJPanel extends javax.swing.JPanel {

    private JPanel CardPanel;
    private PlantReportRequest request;
    public int pop;

    /**
     * Creates new form PlantReportJPanel
     */
    public WritePlantReportJPanel(JPanel a, PlantReportRequest b) {
        this.CardPanel = a;
        this.request = b;
        initComponents();
        subBtn.setEnabled(false);
        animalNameTXT.setText(request.getReport().getName());
        pop = 0;
        this.setBackground(null);
        this.setOpaque(false);
        subBtn.setEnabled(false);
    }

    public void populate() {
        reportTXT.setText(request.getReport().getReportString());
        reportTXT.setEditable(false);
        pop = 1;
    }

    public void checkButton() {
        if (reportTXT.getText() == null || reportTXT.getText().isEmpty() || reportTXT.getText() == "" || reportTXT.getText().equalsIgnoreCase("")) {
            subBtn.setEnabled(false);
        } else {
            subBtn.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animalNameTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTXT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        animalNameTXT.setEditable(false);
        animalNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalNameTXTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Plant Report");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Plant name:");

        backBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        subBtn.setText("Submit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        reportTXT.setColumns(20);
        reportTXT.setRows(5);
        reportTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reportTXTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(reportTXT);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Report:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animalNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(383, 383, 383))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(animalNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        if (pop==0) {
            Component[] componentArray = CardPanel.getComponents();
            Component component = componentArray[componentArray.length - 1];
            BotanistWorkSchedule dwjp = (BotanistWorkSchedule) component;
            dwjp.populateTable();
        } 
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        String aaString = reportTXT.getText();
        if (aaString == null) {
            JOptionPane.showMessageDialog(null, "Please enter your report!");
            return;
        }
        request.getReport().setReportString(aaString);
        request.getReport().setStatus("Checked");
        JOptionPane.showMessageDialog(null, "Submitted successfully!");
        reportTXT.setText("");
        checkButton();

    }//GEN-LAST:event_subBtnActionPerformed

    private void reportTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reportTXTKeyReleased
        // TODO add your handling code here:
        checkButton();
    }//GEN-LAST:event_reportTXTKeyReleased

    private void animalNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalNameTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField animalNameTXT;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea reportTXT;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
