/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.User;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.UserOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonationRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 
import java.util.Calendar; 
import java.text.SimpleDateFormat; 
/**
 *
 * @author tusiyu
 */
public class Donator extends javax.swing.JPanel {

    /**
     * Creates new form Donator
     */
     private UserAccount useraccount;
     private Enterprise enterprise;
     private UserOrganization userorganization;
     private EcoSystem  business;
    public JPanel CardPanel;
    public Donator(JPanel CardPanel,UserAccount useraccount,Enterprise enterprise,UserOrganization userorganization) {
        this.CardPanel = CardPanel;
        this.useraccount =useraccount;
        this.enterprise =enterprise;
        this.userorganization= userorganization;
       
        initComponents();
        nameTextField.setText(useraccount.getPerson().getName());
            jButton1.setEnabled(false);
        this.setOpaque(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    /**
     *   Gong
     */
    public void checkButton() {
        if (nameTextField.getText().isEmpty()||moneyTextField.getText().isEmpty()) {
           jButton1.setEnabled(false);
            return;
        }else{
              jButton1.setEnabled(true);
              moneyTextField.setBackground(Color.white);

        }
       
       

    }
     /**
      * 
      *    Gong
      */
    public boolean isNumber() {
         Pattern p = Pattern.compile("^([1-9][0-9]*)+(.[0-9]{1})?$");
        Matcher m = p.matcher(moneyTextField.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        moneyTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        moneylab = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Donator ");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Name:");

        nameTextField.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("$");

        moneyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moneyTextFieldKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Donate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        moneylab.setForeground(new java.awt.Color(255, 0, 51));
        moneylab.setText("       ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moneylab, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(408, 408, 408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(moneyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneylab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        /**
         *   Gong
         */
         
         if (moneyTextField.getText().isEmpty() || nameTextField.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
            return;
          }
           if (!isNumber()) {
            moneyTextField.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Wrong money pattern");
             
            return;
        }
         
        DonationRequest d = new DonationRequest();
        Date now = new Date();
        d.setRequestDate(now);
        d.setDonationmoney(Double.parseDouble(moneyTextField.getText()));
        d.setSender(useraccount);
        
        useraccount.getWorkQueue().getDonationList().add(d);
        enterprise.getWorkQueue().getDonationList().add(d);

        
      
        JOptionPane.showMessageDialog(null, "Donate Successfully");
        moneyTextField.setBackground(Color.white);
        moneyTextField.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * 
     *   Gong
     */
    private void moneyTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneyTextFieldKeyReleased
        // TODO add your handling code here:
        checkButton();
        if(!isNumber()){
            moneylab.setText("Wrong money pattern!");
        }else{
            moneylab.setText(null);
        }
        
       
    }//GEN-LAST:event_moneyTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField moneyTextField;
    private javax.swing.JLabel moneylab;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables

//    private void populateTable() {
//        DefaultTableModel model = (DefaultTableModel) ETable3.getModel();
//
//        model.setRowCount(0);
//
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
//                Object row[] = new Object[3];
//                row[0] = ua.getUsername();
//                row[1] = ua.getPerson().getName();
//                row[2]=ua.getDonation();
//                ((DefaultTableModel) ETable3.getModel()).addRow(row);
//    }
//        }
//    }
}
