/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.User;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Person.Person;
import Business.Role.UserRole;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author tusiyu
 */
public class SignInPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignInPanel
     */
    public JPanel CardPanel;
    public EcoSystem system;
    public SignInPanel(JPanel CardPanel,EcoSystem system) {
        this.CardPanel = CardPanel;
        this.system = system;
        initComponents();
        subBtn.setEnabled(false);
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      private boolean namePatternCorrect() {
               String PATTERN ="^[a-zA-Z]{1}[a-zA-Z\\s]{0,8}[a-zA-Z]{1}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(ntxt.getText());
          
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
    }

    private boolean usernamePatternCorrect() {
        String PATTERN ="^[a-zA-Z][a-zA-Z0-9]{2,15}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(utxt.getText());
          
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
}
    
    public boolean emailPatternCorrect() {
        Pattern p = Pattern.compile("^([a-z0-9A-Z]+[._a-z0-9A-Z]?[a-z0-9A-Z]+)@([a-z0-9A-Z]+[a-z0-9A-Z_]?[a-z0-9A-Z]+\\.)+[a-zA-Z]{2,}$");
        Matcher m = p.matcher(etxt.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
    }
    
    public boolean passwordCorrect() {
        String PATTERN ="^[A-Za-z0-9_+$]{6,8}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(ptxt.getText());
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ntxt = new javax.swing.JTextField();
        utxt = new javax.swing.JTextField();
        etxt = new javax.swing.JTextField();
        ptxt = new javax.swing.JTextField();
        cptxt = new javax.swing.JTextField();
        subBtn = new javax.swing.JButton();
        bBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        elabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Sign In ");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Name: ");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("User Name:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel4.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel5.setText("Password: ");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel6.setText("Confirm Password: ");

        ntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ntxtKeyReleased(evt);
            }
        });

        utxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utxtActionPerformed(evt);
            }
        });
        utxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                utxtKeyReleased(evt);
            }
        });

        etxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                etxtKeyReleased(evt);
            }
        });

        ptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptxtKeyReleased(evt);
            }
        });

        cptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cptxtKeyReleased(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        subBtn.setText("Submit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        bBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        bBtn.setText("Back");
        bBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBtnActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));

        uname.setForeground(new java.awt.Color(255, 51, 51));
        uname.setText("      ");

        elabel.setForeground(new java.awt.Color(255, 0, 51));
        elabel.setText("                     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(bBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel6)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(etxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(utxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(ntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elabel, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(utxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(etxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(elabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
      public void checkButton() {
        if (ntxt.getText().isEmpty()) {
            subBtn.setEnabled(false);
            return;
        }
        if (utxt.getText().isEmpty()) {
            subBtn.setEnabled(false);
            return;
        }
        if (etxt.getText().isEmpty()) {
            subBtn.setEnabled(false);
            return;
        }
       if(ptxt.getText().isEmpty()){
           subBtn.setEnabled(false);
       }
        
        if (!ptxt.getText().equals(cptxt.getText())) {
            subBtn.setEnabled(false);
            return;
        }
        subBtn.setEnabled(true);

    }
     
     
    private void bBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.removeAll();
//        CardLayout layout = (CardLayout)CardPanel.getLayout();
//        layout.previous(CardPanel);
        
    }//GEN-LAST:event_bBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
       
          if(!namePatternCorrect()){
              JOptionPane.showMessageDialog(null, "Wrong name pattern!");
              return;
           }
          
         if(!usernamePatternCorrect()){
               JOptionPane.showMessageDialog(null, "Wrong user name pattern!");
             return;
          }
           if (!emailPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Wrong email pattern!");
            return;
        }
           if(!passwordCorrect()){
                JOptionPane.showMessageDialog(null, "Your password should have 6 to 8 digits and could contain 0-9，a-z，A-Z，+_$");
            return;
               
           }
       
          
       String name =  ntxt.getText();
       String userName = utxt.getText();
       String pw = ptxt.getText();
       String email = etxt.getText();
       
       
       Person p = new Person();
       p.setTag("User");
       p.setName(name);
       Enterprise enterprise = system.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(0);
       enterprise.getOrganizationDirectory().getOrganizationList().get(0).getUserAccountDirectory().createUserAccount(userName, pw,p, new UserRole()).setEmail(email);

       JOptionPane.showMessageDialog(null, "Successfully Joint us!");
       cptxt.setBackground(Color.white);
       ntxt.setText("");
       utxt.setText("");
       ptxt.setText("");
       etxt.setText("");
       cptxt.setText("");
       
       
    }//GEN-LAST:event_subBtnActionPerformed

    private void cptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptxtKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (ptxt.getText().equals(cptxt.getText())) {
            cptxt.setBackground(Color.green);
        } else {
            cptxt.setBackground(Color.red);
        }
    }//GEN-LAST:event_cptxtKeyReleased

    private void ptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxtKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (cptxt.getText().isEmpty()) {
            return;
        }
        if (cptxt.getText().equals(ptxt.getText())) {
            cptxt.setBackground(Color.green);
        } else {
            cptxt.setBackground(Color.red);
        }
    }//GEN-LAST:event_ptxtKeyReleased

    private void ntxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ntxtKeyReleased
        // TODO add your handling code here:
               if(!namePatternCorrect()){
                   jLabel7.setText("Name is incorrect!");
               }else{
                   jLabel7.setText(null);
               }
    }//GEN-LAST:event_ntxtKeyReleased

    private void utxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utxtActionPerformed

    private void utxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_utxtKeyReleased
        // TODO add your handling code here:
       
               if(!usernamePatternCorrect()){
                   uname.setText("User Name is incorrect!");
               }else{
                   uname.setText(null);
               }
        
    }//GEN-LAST:event_utxtKeyReleased

    private void etxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etxtKeyReleased
        // TODO add your handling code here:
       
        if(!emailPatternCorrect()){
            elabel.setText("Email is incorrect!");
        }else{
            elabel.setText(null);
        }
    }//GEN-LAST:event_etxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBtn;
    private javax.swing.JTextField cptxt;
    private javax.swing.JLabel elabel;
    private javax.swing.JTextField etxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField ntxt;
    private javax.swing.JTextField ptxt;
    private javax.swing.JButton subBtn;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField utxt;
    // End of variables declaration//GEN-END:variables

  
}

