/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.Enterprise.Enterprise;
import Business.Person.Person;
import Business.Role.EmployeeRole;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tusiyu
 */
public class AddFieldGroup extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    private JPanel CardPanel;
    private Enterprise enterprise;
    public AddFieldGroup(JPanel CardPanel, Enterprise enterprise) {
        initComponents();
        this.CardPanel = CardPanel;
        this.enterprise = enterprise;
        cptxt1.setEnabled(false);
        this.setBackground(null);
        this.setOpaque(false);
        subBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public boolean usernamePatternCorrect() {
        String PATTERN ="^[a-zA-Z][a-zA-Z0-9]{2,15}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(untxt.getText());
          
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
}
      public boolean passwordCorrect() {
        String PATTERN ="^[A-Za-z0-9_+$]{6,8}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(iptxt.getText());
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
     }
     
           public void checkButton() {
        if (untxt.getText().isEmpty()) {
            subBtn.setEnabled(false);
            return;
        }
      
       if(iptxt.getText().isEmpty()){
           subBtn.setEnabled(false);
           return;
       }
                
        
        if (!iptxt.getText().equals(cptxt.getText())) {
            subBtn.setEnabled(false);
            return;
        }
      
       
        subBtn.setEnabled(true);

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        untxt = new javax.swing.JTextField();
        subBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cptxt1 = new javax.swing.JTextField();
        iptxt = new javax.swing.JPasswordField();
        cptxt = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("New FieldGroup");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        jLabel3.setText("User Name:");

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        jLabel5.setText("Initial Password: ");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        jLabel6.setText("Confirm Password: ");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        jLabel7.setText("Account Type:");

        subBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        subBtn.setText("Sumbit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cptxt1.setText("FieldGroup");
        cptxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cptxt1ActionPerformed(evt);
            }
        });

        iptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iptxtKeyReleased(evt);
            }
        });

        cptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cptxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(cptxt1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(untxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))))
                .addGap(463, 463, 463))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(untxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(iptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cptxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
         if(!usernamePatternCorrect()){
               JOptionPane.showMessageDialog(null, "Wrong user name pattern!");
             return;
          }
         if(!passwordCorrect()){
                JOptionPane.showMessageDialog(null, "Your password should have 6 to 8 digits and could contain 0-9，a-z，A-Z，+_$");
            return;
               
           }

       
        String uname = untxt.getText();       
        String ip = iptxt.getText();
        String cp = cptxt.getText();    
        Person p = new Person();
        p.setTag("FieldGroup");
        p.setName(uname);
        enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().createUserAccount(uname,cp, p, new EmployeeRole());
        JOptionPane.showMessageDialog(null, "A New Employee account is created!");
        untxt.setText("");
        iptxt.setText("");
        cptxt.setText("");
        subBtn.setEnabled(false);
        cptxt.setBackground(Color.white);

    }//GEN-LAST:event_subBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        Component[] componentArray = CardPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManagerPanel dwjp = (ManagerPanel) component;
        dwjp.populateFieldGroup();
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cptxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cptxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cptxt1ActionPerformed

    private void iptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iptxtKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (cptxt.getText().isEmpty()) {
            return;
        }
        if (cptxt.getText().equals(iptxt.getText())) {
            cptxt.setBackground(Color.green);
        } else {
            cptxt.setBackground(Color.red);
        }
    }//GEN-LAST:event_iptxtKeyReleased

    private void cptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptxtKeyReleased
        // TODO add your handling code here:
         checkButton();
        if (iptxt.getText().equals(cptxt.getText())) {
            cptxt.setBackground(Color.green);
        } else {
            cptxt.setBackground(Color.red);
        }
    }//GEN-LAST:event_cptxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cptxt;
    private javax.swing.JTextField cptxt1;
    private javax.swing.JPasswordField iptxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton subBtn;
    private javax.swing.JTextField untxt;
    // End of variables declaration//GEN-END:variables
}
