/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.Enterprise.Enterprise;
import Business.Species.IndividualP;
import Business.Species.PlantSpecies;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gong
 */
public class AddPlantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPlantJPanel
     */
    private JPanel Cardpanel;
    private PlantSpecies p;
    private Enterprise enterprise;

    public AddPlantJPanel(JPanel Cardpanel, PlantSpecies p,Enterprise c) {
        initComponents();
        this.Cardpanel = Cardpanel;
        this.enterprise=c;
        this.p = p;
        Addbtn.setEnabled(false);
        this.setBackground(null);
        this.setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public boolean namePatternCorrect() {
        Pattern p = Pattern.compile("^[a-zA-Z]{2,20}$");
        Matcher m = p.matcher(ntxt.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
    }


    public void checkButton() {
        if (ntxt.getText().isEmpty() ) {
            Addbtn.setEnabled(false);
            return;
        } else {
            Addbtn.setEnabled(true);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelab = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        maxlab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ntxt = new javax.swing.JTextField();
        minlab = new javax.swing.JLabel();

        namelab.setForeground(new java.awt.Color(255, 51, 51));

        Addbtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        maxlab.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N
        jLabel3.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("New  Plant");

        ntxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ntxtKeyReleased(evt);
            }
        });

        minlab.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(ntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxlab, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namelab, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(minlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(namelab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(minlab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(maxlab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        if (ntxt.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
            return;
        }
        if (!namePatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Wrong name pattern!");
            return;
        }

        

        for (PlantSpecies an : enterprise.getPlantDirectory().getPlantDir()) {
            String name = ntxt.getText()+"."+an.getName();
            if (an == p) {
                IndividualP plant = new IndividualP();
                plant.setName(name);
                an.getPlantIndividualDirectory().getPlantList().add(plant);
            }
        }

        JOptionPane.showMessageDialog(null, "Successfully!");
        ntxt.setText("");
        Addbtn.setText("");

    }//GEN-LAST:event_AddbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Cardpanel.remove(this);
        Component[] componentArray = Cardpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PlantPanel dwjp = (PlantPanel) component;
        dwjp.populate();
        CardLayout layout = (CardLayout) Cardpanel.getLayout();
        layout.previous(Cardpanel);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ntxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ntxtKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (!namePatternCorrect()) {
            namelab.setText("Name is incorrect!");
        } else {
            namelab.setText(null);
        }
    }//GEN-LAST:event_ntxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maxlab;
    private javax.swing.JLabel minlab;
    private javax.swing.JLabel namelab;
    private javax.swing.JTextField ntxt;
    // End of variables declaration//GEN-END:variables
}
