/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.Enterprise.Enterprise;
import Business.Report.AnimalReport;
import Business.Species.AnimalSpecies;
import Business.Species.IndividualA;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AnimalReportRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tusiyu
 */
public class AnimalPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnimalPanel
     */
    private AnimalSpecies a;
    private JPanel Cardpanel;
    public Enterprise enterprise;
    private UserAccount account;

    public AnimalPanel(JPanel Cardpanel, AnimalSpecies a, Enterprise enterprise, UserAccount account) {
        this.Cardpanel = Cardpanel;
        this.a = a;
        this.enterprise = enterprise;
        this.account = account;
        initComponents();
        name.setText(a.getName());
        this.setBackground(null);
        this.setOpaque(false);
        populate();
        
    }

    public void populate() {
        boolean b;
        DefaultTableModel dtm = (DefaultTableModel) individual.getModel();
        dtm.setRowCount(0);
        for (IndividualA an : a.getAnimalIndividualDir().getAnimalList()) {
            b = false;
            for (AnimalReport ar : enterprise.getReportDirectory().getReportDirectory()) {
                if (ar.getName() == an.getName() || ar.getName().equalsIgnoreCase(an.getName())) {
                    Object[] row = new Object[7];
                    row[0] = an;
                    row[1] = ar.getName();
                    row[2] = ar.getMin_bp();
                    row[3] = ar.getMax_bp();
                    row[4] = ar.getBody_temp();
                    row[5] = ar.getWeight();
                    row[6] = ar.getHeight();
                    dtm.addRow(row);
                    b = true;
                    break;
                }
            }
            if (b == false) {
                Object[] row = new Object[7];
                row[0] = an;
                row[1] = an.getName();
                row[2] = an.getMin_bp();
                row[3] = an.getMax_bp();
                row[4] = an.getTemp();
                row[5] = an.getWeight();
                row[6] = an.getHeight();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        individual = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        name.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N

        individual.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        individual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Min_BP", "Max_BP", "Body Temperature", "Wieght", "Height"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(individual);

        jButton2.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cardpanel.remove(this);
        Component[] componentArray = Cardpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ExecutorPanel dwjp = (ExecutorPanel) component;
        dwjp.populateAnimal();
        CardLayout layout = (CardLayout) Cardpanel.getLayout();
        layout.previous(Cardpanel);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     *
     * Gong 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AddAnimalJPanel panel = new AddAnimalJPanel(Cardpanel, a, enterprise, account);
        Cardpanel.add("AddAnimalPanel", panel);
        CardLayout layout = (CardLayout) Cardpanel.getLayout();
        layout.next(Cardpanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = individual.getSelectedRow();
        if (selectedRow >= 0) {
            IndividualA a = (IndividualA) individual.getValueAt(selectedRow, 0);
            for(AnimalSpecies an: enterprise.getAnimalDirectory().getAnimalList())
                an.getAnimalIndividualDir().getAnimalList().remove(a);
                    
            populate();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTable individual;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
