/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Person.Person;
import Business.Species.AnimalDirectory;
import Business.Species.PlantDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CommentsWorkRequest;
import Business.WorkQueue.DonationRequest;
import Business.WorkQueue.FundingRequest;
import Business.WorkQueue.ReservationWorkRequest;
import com.sun.org.apache.xml.internal.utils.StringBufferPool;
import java.awt.CardLayout;
import java.nio.file.FileVisitResult;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author tusiyu
 */
public class ManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerPanel2
     */
    private JPanel CardPanel;
    private Enterprise enterprise;
    private Double salaryTotal;
    private UserAccount account;
    private EcoSystem system;
    private Double funding = 0.0;
    private Double totalMoney;
    private Double df;

    public ManagerPanel(JPanel CardPanel, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.account = account;
        this.CardPanel = CardPanel;
        this.enterprise = enterprise;
        this.system = system;
        totalMoney = totalDonation();
        totaldonation.setText(String.valueOf(totalDonation()));
        total.setText(String.valueOf(totalMoney));
        df = totalMoney;
        total.setEnabled(false);
        totaldonation.setEnabled(false);
        this.setBackground(null);
        this.setOpaque(false);
        populateUser();
        populateEmployee();
        populateBudget();
        populateSalary();
        populateRequest();
        populateFieldGroup();
        populateComments();

        this.setOpaque(false);
        SpeciesPanel.setOpaque(false);
        AbnormalPanel.setOpaque(false);
        Report.setOpaque(false);
        Request.setOpaque(false);
        Donation.setOpaque(false);
        jPanel1.setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        SpeciesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        user = new javax.swing.JTable();
        AbnormalPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employee = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Report = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ff = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        Request = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        request = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        commentsTXT = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        Donation = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        salary = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Assignbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totaldonation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        budget = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        savailable = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel1.setText("Users");

        jButton2.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Account Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        user.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(user);

        javax.swing.GroupLayout SpeciesPanelLayout = new javax.swing.GroupLayout(SpeciesPanel);
        SpeciesPanel.setLayout(SpeciesPanelLayout);
        SpeciesPanelLayout.setHorizontalGroup(
            SpeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeciesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SpeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SpeciesPanelLayout.createSequentialGroup()
                        .addGroup(SpeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        SpeciesPanelLayout.setVerticalGroup(
            SpeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpeciesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(SpeciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );

        jTabbedPane1.addTab("ManagerUsers", SpeciesPanel);

        employee.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Job Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(employee);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Employees");

        jButton6.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbnormalPanelLayout = new javax.swing.GroupLayout(AbnormalPanel);
        AbnormalPanel.setLayout(AbnormalPanelLayout);
        AbnormalPanelLayout.setHorizontalGroup(
            AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbnormalPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(AbnormalPanelLayout.createSequentialGroup()
                        .addGroup(AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        AbnormalPanelLayout.setVerticalGroup(
            AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbnormalPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(AbnormalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AbnormalPanelLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ManagerEmployees", AbnormalPanel);

        ff.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "FieldGroup"
            }
        ));
        ff.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(ff);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Field Group");

        jButton4.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton14.setText("Back");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportLayout = new javax.swing.GroupLayout(Report);
        Report.setLayout(ReportLayout);
        ReportLayout.setHorizontalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(238, 238, 238))
        );
        ReportLayout.setVerticalGroup(
            ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ReportLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );

        jTabbedPane1.addTab("ManageFieldGroup", Report);

        request.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        request.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Funding", "Expecting Date", "Description", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(request);

        jButton12.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton13.setText("Delete");

        jButton16.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton16.setText("Back");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel13.setText("Funding Requests");

        javax.swing.GroupLayout RequestLayout = new javax.swing.GroupLayout(Request);
        Request.setLayout(RequestLayout);
        RequestLayout.setHorizontalGroup(
            RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RequestLayout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        RequestLayout.setVerticalGroup(
            RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton16)
                .addContainerGap())
        );

        jTabbedPane1.addTab("FundingRequest", Request);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel4.setText("Comments from users");

        commentsTXT.setColumns(20);
        commentsTXT.setRows(5);
        jScrollPane8.setViewportView(commentsTXT);

        jButton17.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(498, 498, 498))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );

        jTabbedPane1.addTab("UsersComments", jPanel1);

        salary.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        salary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Salary"
            }
        ));
        jScrollPane5.setViewportView(salary);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel5.setText("Employees");

        Assignbtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        Assignbtn.setText("Assign");
        Assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignbtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel6.setText("Donation in Total: ");

        jLabel7.setText("$");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel8.setText("Budget: ");

        budget.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        budget.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Total", "Percentage"
            }
        ));
        budget.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(budget);

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel9.setText("Total Money Available:");

        jLabel10.setText("$");

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel11.setText("Salary Available:");

        jButton15.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel12.setText("$");

        javax.swing.GroupLayout DonationLayout = new javax.swing.GroupLayout(Donation);
        Donation.setLayout(DonationLayout);
        DonationLayout.setHorizontalGroup(
            DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonationLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(DonationLayout.createSequentialGroup()
                        .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DonationLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(215, 215, 215)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(savailable, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(Assignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DonationLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totaldonation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(231, 231, 231))
        );
        DonationLayout.setVerticalGroup(
            DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonationLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totaldonation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(savailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(15, 15, 15)
                .addGroup(DonationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Assignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Finance", Donation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = ff.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount a = (UserAccount) ff.getValueAt(selectedRow, 0);
            enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList().remove(a);
            populateFieldGroup();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
              
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void AssignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignbtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = salary.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount studentselected = (UserAccount) salary.getValueAt(selectedRow, 0);
            if(studentselected.getPerson().getSalary()!=0.0){
                JOptionPane.showMessageDialog(null, "The salary is assigned");
            }
            else{
            String i = studentselected.getPerson().getName();
            for (UserAccount u : enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList()) {
                if (u.getPerson().getName().equalsIgnoreCase(i)) {
                    Person p = u.getPerson();
                    String s = JOptionPane.showInputDialog(null, "Salary", "Salary", WIDTH);
                    Double sa = Double.parseDouble(s);
                    if (sa <= salaryTotal) {
                        p.setSalary(p.getSalary() + sa);
                        salaryTotal = salaryTotal - sa;
                        savailable.setText(String.valueOf(salaryTotal));
                        savailable.setEnabled(false);
                        totalMoney = totalMoney - sa;
                        total.setText(String.valueOf(totalMoney));
                        populateEmployee();
//                        populateBudget();
                        populateSalary();
                        JOptionPane.showMessageDialog(null, "The salary is assigned!");

                        return;
                    } else {
                        JOptionPane.showMessageDialog(null, "The salary is not proper!");
                        return;
                    }
                }
            }
        } }else {
            JOptionPane.showMessageDialog(null, "Select one row", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_AssignbtnActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        System.out.println(account.getUsername());
        RequestPanel panel = new RequestPanel(CardPanel, account, enterprise, system);
        panel.setBackground(null);
        panel.setOpaque(false);
        CardPanel.add("RequestPanel", panel);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = user.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount a = (UserAccount) user.getValueAt(selectedRow, 0);
            enterprise.getOrganizationDirectory().getOrganizationList().get(0).getUserAccountDirectory().getUserAccountList().remove(a);
            populateUser();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AddEmployee panel = new AddEmployee(CardPanel, enterprise);
        panel.setBackground(null);
        panel.setOpaque(false);
        CardPanel.add("AddEmployee", panel);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int selectedRow = employee.getSelectedRow();
        if (selectedRow >= 0) {
            UserAccount a = (UserAccount) employee.getValueAt(selectedRow, 0);
            enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList().remove(a);
            populateEmployee();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AddFieldGroup panel = new AddFieldGroup(CardPanel, enterprise);
        panel.setBackground(null);
        panel.setOpaque(false);
        CardPanel.add("AddFieldGroup", panel);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_jButton17ActionPerformed

    public void populateEmployee() {
        DefaultTableModel dtm = (DefaultTableModel) employee.getModel();
        dtm.setRowCount(0);
//        enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList();
        for (UserAccount u : enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList()) {
//            System.out.println(u.getUsername());
            if (u.getPerson().getTag() != "FieldGroup") {
                Object[] row = new Object[4];
                row[0] = u;
                row[1] = u.getPerson().getName();
                row[2] = u.getEmail();
                row[3] = u.getPerson().getTag();
                dtm.addRow(row);
            }
        }

    }

    public void populateUser() {
        DefaultTableModel dtm = (DefaultTableModel) user.getModel();
        dtm.setRowCount(0);
        for (UserAccount u : enterprise.getOrganizationDirectory().getOrganizationList().get(0).getUserAccountDirectory().getUserAccountList()) {
//            System.out.println(u.getUsername());
            Object[] row = new Object[4];
            row[0] = u;
            row[1] = u.getPerson().getName();
            row[2] = u.getEmail();
            row[3] = u.getPerson().getTag();
            dtm.addRow(row);
        }

    }

    private void populateBudget() {
        DefaultTableModel dtm = (DefaultTableModel) budget.getModel();
        dtm.setRowCount(0);
        Double budget = df;
        Map<String, Double> bud = new HashMap<String, Double>();
        bud.put("National Park Daily Expense", 0.4);
        bud.put("Reseache fee", 0.25);
        bud.put("Employee Salary", 0.25);
        bud.put("Protention & Development", 0.1);
        for (String k : bud.keySet()) {
            if (k.equalsIgnoreCase("Employee Salary")) {
                salaryTotal = bud.get(k) * budget;
                savailable.setText(String.valueOf(salaryTotal));
                savailable.setEnabled(false);
            }
            Object[] row = new Object[3];
            row[0] = k;
            row[1] = String.format("%.2f", bud.get(k) * budget);
            row[2] = bud.get(k) * 100 + "%";
            dtm.addRow(row);
        }

    }

    private void populateSalary() {
        DefaultTableModel dtm = (DefaultTableModel) salary.getModel();
        dtm.setRowCount(0);

        for (UserAccount u : enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList()) {

            Object[] row = new Object[3];
            row[0] = u;
            row[1] = u.getPerson().getName();
            row[2] = u.getPerson().getSalary();
            dtm.addRow(row);

        }
    }

    public double totalDonation() {
        double sum = 0;
        for (DonationRequest d: enterprise.getWorkQueue().getDonationList()) {
            sum = sum + d.getDonationmoney();
        }
        return sum;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbnormalPanel;
    private javax.swing.JButton Assignbtn;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Donation;
    private javax.swing.JPanel Report;
    private javax.swing.JPanel Request;
    private javax.swing.JPanel SpeciesPanel;
    private javax.swing.JTable budget;
    private javax.swing.JTextArea commentsTXT;
    private javax.swing.JTable employee;
    private javax.swing.JTable ff;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable request;
    private javax.swing.JTable salary;
    private javax.swing.JTextField savailable;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totaldonation;
    private javax.swing.JTable user;
    // End of variables declaration//GEN-END:variables

    public void populateRequest() {
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        DefaultTableModel dtm = (DefaultTableModel) request.getModel();
        dtm.setRowCount(0);
        Enterprise enterprise1 = system.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().get(1);
        for (FundingRequest fr : enterprise1.getWorkQueue().getFundingRequestList()) {
            Object[] row = new Object[5];
            row[0] = fr;
            row[1] = fr.getFunding();
            row[2] = sdf.format(fr.getRequestDate());
            if (String.valueOf(fr.getResolveDate()) == "") {
                row[3] = "Pending";
            }
            row[3] = fr.getResolveDate();
            row[3] = fr.getDescription();
            row[4] = fr.getStatus();
            dtm.addRow(row);
        }

        for (FundingRequest fr : enterprise1.getWorkQueue().getFundingRequestList()) {
            if (fr.getStatus().equalsIgnoreCase("Approved")) {
                funding = funding + fr.getFunding();
            }
        }
        totalMoney = totalMoney + funding;
        df = df + funding;
        total.setText(String.valueOf(totalMoney));
        populateBudget();
    }

    public void populateFieldGroup() {
        DefaultTableModel dtm = (DefaultTableModel) ff.getModel();
        dtm.setRowCount(0);
        enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList();
        for (UserAccount u : enterprise.getOrganizationDirectory().getOrganizationList().get(1).getUserAccountDirectory().getUserAccountList()) {
            if (u.getPerson().getTag().equalsIgnoreCase("FieldGroup")) {
                Object[] row = new Object[2];
                row[0] = u;
                row[1] = u.getPerson().getName();
                dtm.addRow(row);
            }
        }
    }

    private void populateComments() {
        commentsTXT.setEditable(false);
        String commentsString = "";
        if (enterprise.getOrganizationDirectory().getOrganizationList().get(0).getWorkQueue().getCommentsWorkRequests().size() != 0) {
            for (CommentsWorkRequest a : enterprise.getOrganizationDirectory().getOrganizationList().get(0).getWorkQueue().getCommentsWorkRequests()) {
                commentsString += a.toString() + ":\n" + a.getMessage() + "\n\n";
            }
        }
        commentsTXT.setText(commentsString);
    }

}
