/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.Enterprise.Enterprise;
import Business.Report.PlantReport;
import Business.Species.AnimalSpecies;
import Business.Species.IndividualA;
import Business.Species.IndividualP;
import Business.Species.PlantSpecies;
import Business.WorkQueue.AnimalReportRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tusiyu
 */
public class PlantPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnimalPanel
     */
    private PlantSpecies p;
    private JPanel Cardpanel;
    private Enterprise enterprise;

    public PlantPanel(JPanel Cardpanel, PlantSpecies p, Enterprise enterprise) {
        this.Cardpanel = Cardpanel;
        this.p = p;
        this.enterprise = enterprise;
        initComponents();
        name.setText(p.getName());
        this.setBackground(null);
        this.setOpaque(false);
        populate();
    }

    public void populate() {
        boolean b;
        DefaultTableModel dtm = (DefaultTableModel) individual.getModel();
        dtm.setRowCount(0);
        for (IndividualP an : p.getPlantIndividualDirectory().getPlantList()) {
            b = false;
            for (PlantReport ar : enterprise.getReportDirectory().getReportDirectory1()) {
                if (ar.getName() == an.getName() || ar.getName().equalsIgnoreCase(an.getName())) {
                    Object[] row = new Object[3];
                    row[0] = an;
                    row[1] = ar.getName();
                    if (ar.getCheckAbnormal() == 0) {
                        row[2] = "Normal";
                    } else if (ar.getCheckAbnormal() == 1) {
                        row[2] = "Abormal";
                    } else {
                        row[2] = "Unchecked";
                    }
                    dtm.addRow(row);
                    b = true;
                    break;
                }
            }
            if (b == false) {
                Object[] row = new Object[3];
                row[0] = an;
                row[1] = an.getName();
                row[2] = "Unchecked";
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        individual = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        addbtn1 = new javax.swing.JButton();

        name.setFont(new java.awt.Font("Lucida Bright", 2, 18)); // NOI18N

        individual.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        individual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Min_Temperatrue", "Max_Temperature"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        individual.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(individual);

        jButton2.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        addbtn1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        addbtn1.setText("Delete");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(addbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Cardpanel.remove(this);
        //CardLayout layout = (CardLayout)Cardpanel.getLayout();
        // layout.previous(Cardpanel);
        Cardpanel.remove(this);
        Component[] componentArray = Cardpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ExecutorPanel dwjp = (ExecutorPanel) component;
        dwjp.populatePlant();
        CardLayout layout = (CardLayout) Cardpanel.getLayout();
        layout.previous(Cardpanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        AddPlantJPanel panel = new AddPlantJPanel(Cardpanel, p, enterprise);
        Cardpanel.add("AddAnimalPanel", panel);
        CardLayout layout = (CardLayout) Cardpanel.getLayout();
        layout.next(Cardpanel);

    }//GEN-LAST:event_addbtnActionPerformed

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = individual.getSelectedRow();
        if (selectedRow >= 0) {
            IndividualP a = (IndividualP) individual.getValueAt(selectedRow, 0);
            for(PlantSpecies an: enterprise.getPlantDirectory().getPlantDir())
                an.getPlantIndividualDirectory().getPlantList().remove(a);                  
            populate();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_addbtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton addbtn1;
    private javax.swing.JTable individual;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
