/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Vet;

import Business.Enterprise.Enterprise;
import Business.Organization.EmployeeOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VolunteerWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YueZheng
 */
public class VolunteerRequestJPanel extends javax.swing.JPanel {

    private JPanel CardPanel;
    private EmployeeOrganization organization;
    private Enterprise enterprise;
    private UserAccount account;
    /**
     * Creates new form VolunteerRequestJPanel
     */
    public VolunteerRequestJPanel(JPanel CardPanel,UserAccount account,EmployeeOrganization organization,Enterprise enterprise) {
        this.CardPanel = CardPanel;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;  
        initComponents();
        this.setBackground(null);
        this.setOpaque(false);
        populateVolunteerRequest();
        
    }


    public void populateVolunteerRequest(){

        DefaultTableModel model = (DefaultTableModel) vrequest.getModel();
        model.setRowCount(0);
        for(VolunteerWorkRequest vr:enterprise.getOrganizationDirectory().getOrganizationList().get(1).getWorkQueue().getVolunteerRequestList()){
            if(vr.getProject().getStatus()=="Finished"){
                vr.setStatus("Declined");
            }
                
            else{
                if(vr.getReceiver()==account)
            {
                Object[] row = new Object[4];
                row[0] = vr;
                row[1] = vr.getSender().getUsername();
                row[2] = vr.getProject().getAvailableNum();
                row[3] = vr.getStatus();
                model.addRow(row);
                }
               
            }}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vrequest = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        declineBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Volunteer Applications");

        vrequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        vrequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Projecrt Name", "User Name", "Available People", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vrequest.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(vrequest);
        if (vrequest.getColumnModel().getColumnCount() > 0) {
            vrequest.getColumnModel().getColumn(0).setResizable(false);
            vrequest.getColumnModel().getColumn(1).setResizable(false);
            vrequest.getColumnModel().getColumn(2).setResizable(false);
        }

        backBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        approveBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        approveBtn.setText("Approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });

        declineBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        declineBtn.setText("Decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(179, 179, 179)
                            .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = vrequest.getSelectedRow();
        if (selectedRow >= 0){ 
             VolunteerWorkRequest request = (VolunteerWorkRequest) vrequest.getValueAt(selectedRow, 0);
             
             int number = 0;
             number = request.getProject().getAvailableNum();
             if(number>0){
             request.setStatus("Approved");
             number--;
             request.getProject().setAvailableNum(number);
             populateVolunteerRequest();}
             else{
                  JOptionPane.showMessageDialog(null,"Project is fully resgistered");
             }
        }
        else{
            JOptionPane.showMessageDialog(null,"Select one row", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_approveBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = vrequest.getSelectedRow();
        if (selectedRow >= 0){ 
             VolunteerWorkRequest request = (VolunteerWorkRequest) vrequest.getValueAt(selectedRow, 0);
             request.setStatus("Decline");
             populateVolunteerRequest();
        }
        else{
            JOptionPane.showMessageDialog(null,"Select one row", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_declineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton declineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vrequest;
    // End of variables declaration//GEN-END:variables
}
