/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Geologist;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClimateReportRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class ClimateReportJPanel extends javax.swing.JPanel {

    private JPanel CardPanel;
    private UserAccount account;
    private Enterprise enterprise;
    private SimpleDateFormat sdf;

    /**
     * Creates new form ClimateReportJPanel
     */
    public ClimateReportJPanel(JPanel a, Enterprise b, UserAccount c) {
        this.account = c;
        this.enterprise = b;
        this.CardPanel = a;
        initComponents();
        submitBtn.setEnabled(false);
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        titleLabel.setText("Today's Report " + sdf.format(new Date()));
        this.setBackground(null);
        this.setOpaque(false);

    }

    public boolean highPatternCorrect() {
        Pattern p = Pattern.compile("^([1-9][0-9]*)+(.[0-9]{1})?$");
        Matcher m = p.matcher(highTempTXT.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
    }

    public boolean lowPatternCorrect() {
        Pattern p = Pattern.compile("^([1-9][0-9]*)+(.[0-9]{1})?$");
        Matcher m = p.matcher(lowTempTXT.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
    }

    public boolean humPatternCorrect() {
        Pattern p = Pattern.compile("^([1-9][0-9]*)+(.[0-9]{1})?$");
        Matcher m = p.matcher(humidityTXT.getText());
        boolean b = m.matches();
        if (b == false) {
            return false;
        }
        return true;
    }

    public void checkButton() {
        if (highTempTXT.getText().isEmpty() || lowTempTXT.getText().isEmpty() || humidityTXT.getText().isEmpty()) {
            submitBtn.setEnabled(false);
            return;
        }
        submitBtn.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        highTempTXT = new javax.swing.JTextField();
        lowTempTXT = new javax.swing.JTextField();
        humidityTXT = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        highLabel = new javax.swing.JLabel();
        lowLabel = new javax.swing.JLabel();
        humidityLabel = new javax.swing.JLabel();

        titleLabel.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        titleLabel.setText("Today's Report");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("High temperature:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Low temperature:");

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel4.setText("Humidity:");

        highTempTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                highTempTXTKeyReleased(evt);
            }
        });

        lowTempTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lowTempTXTKeyReleased(evt);
            }
        });

        humidityTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                humidityTXTKeyReleased(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        highLabel.setForeground(new java.awt.Color(255, 0, 0));
        highLabel.setText("                     ");

        lowLabel.setForeground(new java.awt.Color(255, 0, 51));
        lowLabel.setText("                     ");

        humidityLabel.setForeground(new java.awt.Color(255, 0, 51));
        humidityLabel.setText("                     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(highTempTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowTempTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(humidityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(highTempTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(highLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lowTempTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(humidityTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(humidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        //if (highTempTXT.getText() != null && lowTempTXT.getText() != null && humidityTXT.getText()!=null) {
        if (!lowPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Wrong Low Temperature pattern!");
            return;
        }

        if (!highPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Wrong High Temperature pattern!");
            return;
        }
        if (!humPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Wrong Humidity pattern!");
            return;
        }
        if (Double.parseDouble(highTempTXT.getText()) < Double.parseDouble(lowTempTXT.getText())) {
            JOptionPane.showMessageDialog(null, "Low Temperature shuould be smaller than High Temperature!");
            return;
        }

        ClimateReportRequest cc = new ClimateReportRequest();
        cc.getReport().setMax_t(Double.parseDouble(highTempTXT.getText()));
        cc.getReport().setMin_t(Double.parseDouble(lowTempTXT.getText()));
        cc.getReport().setHumidity(Double.parseDouble(humidityTXT.getText()));
        cc.getReport().setDate(new Date());
        cc.getReport().setStatus("Submitted");
        cc.setType("climate");
        if (account.getWorkQueue().getClimateReportRequests().size() != 0) {
            account.getWorkQueue().getClimateReportRequests().set(0, cc);
            enterprise.getWorkQueue().getClimateReportRequests().set(0, cc);
        } else {
            account.getWorkQueue().getClimateReportRequests().add(cc);
            enterprise.getWorkQueue().getClimateReportRequests().add(cc);
        }
        JOptionPane.showMessageDialog(null, "Successfully submitted!");
        highTempTXT.setText("");
        lowTempTXT.setText("");
        humidityTXT.setText("");
        submitBtn.setEnabled(false);
        
        
        


    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void highTempTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_highTempTXTKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (!highPatternCorrect()) {
            highLabel.setText("High Temperature is incorrect!");
        } else {
            highLabel.setText("");
        }

    }//GEN-LAST:event_highTempTXTKeyReleased

    private void lowTempTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowTempTXTKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (!lowPatternCorrect()) {
            lowLabel.setText("Low Temperature is incorrect!");
        } else {
            lowLabel.setText("");
        }
    }//GEN-LAST:event_lowTempTXTKeyReleased

    private void humidityTXTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_humidityTXTKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (!humPatternCorrect()) {
            humidityLabel.setText("Humidity is incorrect!");
        } else {
            humidityLabel.setText("");
        }
    }//GEN-LAST:event_humidityTXTKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel highLabel;
    private javax.swing.JTextField highTempTXT;
    private javax.swing.JLabel humidityLabel;
    private javax.swing.JTextField humidityTXT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lowLabel;
    private javax.swing.JTextField lowTempTXT;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
