/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.Geologist;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Interface.Employee.EmployeeAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class GeologistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel CardPanel;
    private Enterprise enterprise;
    private UserAccount account;

    /**
     * Creates new form GeologistWorkAreaJPanel
     */
    public GeologistWorkAreaJPanel(JPanel CardPanel, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.CardPanel = CardPanel;
        this.enterprise = enterprise;
        this.account = account;
         this.setBackground(null);
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reportBtn = new javax.swing.JButton();
        myAccBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Geologist Work Area");

        reportBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        reportBtn.setText("Send Today's Report");
        reportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBtnActionPerformed(evt);
            }
        });

        myAccBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        myAccBtn.setText("My Account");
        myAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(220, 220, 220)
                            .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(myAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        ClimateReportJPanel eajp = new ClimateReportJPanel(CardPanel, enterprise ,account);
        CardPanel.add("ClimateReportJPanel", eajp);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);        
    }//GEN-LAST:event_reportBtnActionPerformed

    private void myAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccBtnActionPerformed
        // TODO add your handling code here:
        EmployeeAccountJPanel eajp = new EmployeeAccountJPanel(CardPanel, account);
        CardPanel.add("EmployeeAccountJPanel", eajp);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_myAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton myAccBtn;
    private javax.swing.JButton reportBtn;
    // End of variables declaration//GEN-END:variables
}
