/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author tusiyu
 */
public class EmployeePasswordChange extends javax.swing.JPanel {

    /**
     * Creates new form EmployeePasswordChange
     */
    private JPanel CardJPanel;
    private UserAccount useraccount;
    public EmployeePasswordChange(JPanel CardJPanel,UserAccount useraccount) {
        initComponents();
        this.CardJPanel = CardJPanel;
        this.useraccount = useraccount;
        this.setBackground(null);
        this.setOpaque(false);
        subBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
    public boolean passwordCorrect() {
        String PATTERN ="^[A-Za-z0-9_+$]{6,8}$";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(nptxt.getText());
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
     }
    
     public void checkButton() {
        if (nptxt.getText().isEmpty()) {
            subBtn.setEnabled(false);
            return;
        }
       
       if(cp.getText().isEmpty()){
           subBtn.setEnabled(false);
       }
        
        if (!nptxt.getText().equals(cp.getText())) {
            subBtn.setEnabled(false);
            return;
        }
        subBtn.setEnabled(true);

    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nptxt = new javax.swing.JPasswordField();
        cp = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Change Password");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Comfirm New Password:");

        nptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nptxtKeyReleased(evt);
            }
        });

        cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        subBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        subBtn.setText("Submit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(106, 106, 106)
                                .addComponent(nptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
         if(!passwordCorrect()){
                JOptionPane.showMessageDialog(null, "Your password should have 6 to 8 digits and could contain 0-9，a-z，A-Z，+_$");
            return;
               
           }
        String pw = cp.getText();
        useraccount.setPassword(pw);
        JOptionPane.showMessageDialog(null, "Successfully Changed!");
        nptxt.setText("");
        cp.setText("");
        cp.setBackground(Color.white);
    }//GEN-LAST:event_subBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardJPanel.remove(this);
        CardLayout layout=(CardLayout) CardJPanel.getLayout();
        layout.previous(CardJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nptxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nptxtKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (cp.getText().isEmpty()) {
            return;
        }
        if (cp.getText().equals(nptxt.getText())) {
            cp.setBackground(Color.green);
        } else {
            cp.setBackground(Color.red);
        }
    }//GEN-LAST:event_nptxtKeyReleased

    private void cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpKeyReleased
        // TODO add your handling code here:
        checkButton();
        if (nptxt.getText().equals(cp.getText())) {
            cp.setBackground(Color.green);
        } else {
            cp.setBackground(Color.red);
        }
    }//GEN-LAST:event_cpKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField nptxt;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
