/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.FieldTeam;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AnimalReportRequest;
import Business.WorkQueue.PlantReportRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YueZheng
 */
public class CheckAlertsJPanel extends javax.swing.JPanel {

    private JPanel cardJPanel;
    private Enterprise enterprise;
    private UserAccount account;

    /**
     * Creates new form checkAlertsJPanel
     */
    public CheckAlertsJPanel(JPanel cardJPanel, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.account = account;
        this.cardJPanel = cardJPanel;
        this.enterprise = enterprise;
        populateAnimalTable();
        populatePlantTable();
        this.setBackground(null);
        this.setOpaque(false);
    }

    public void populateAnimalTable() {
        DefaultTableModel model = (DefaultTableModel) animalTable.getModel();
        model.setRowCount(0);
        for (AnimalReportRequest request : account.getWorkQueue().getAbnormalAnimalsRequest().getAnimalReportRequests()) {
            Object[] row = new Object[2];
            row[0] = request;
            row[1] = request.getStatus();
            model.addRow(row);
        }

    }

    public void populatePlantTable() {
        DefaultTableModel model = (DefaultTableModel) plantTable.getModel();
        model.setRowCount(0);
        for (PlantReportRequest request : account.getWorkQueue().getAbnormalPlantsRequest().getPlantReportRequests()) {
            Object[] row = new Object[2];
            row[0] = request;
            row[1] = request.getStatus();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        animalTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        doneAnimalBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        plantTable = new javax.swing.JTable();
        donePlantBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Alerts");

        animalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal", "Status"
            }
        ));
        jScrollPane1.setViewportView(animalTable);

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        doneAnimalBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        doneAnimalBtn.setText("Done");
        doneAnimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneAnimalBtnActionPerformed(evt);
            }
        });

        plantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plant", "Status"
            }
        ));
        jScrollPane2.setViewportView(plantTable);

        donePlantBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        donePlantBtn.setText("Done");
        donePlantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donePlantBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Abnormal Animals:");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Abnormal Plants:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(doneAnimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donePlantBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doneAnimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donePlantBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardJPanel.remove(this);
        CardLayout layout = (CardLayout) cardJPanel.getLayout();
        layout.previous(cardJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doneAnimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneAnimalBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = animalTable.getSelectedRow();
        if (selectedRow >= 0) {
            AnimalReportRequest a = (AnimalReportRequest) animalTable.getValueAt(selectedRow, 0);
            a.setStatus("Handled");
            populateAnimalTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }

    }//GEN-LAST:event_doneAnimalBtnActionPerformed

    private void donePlantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donePlantBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = plantTable.getSelectedRow();
        if (selectedRow >= 0) {
            PlantReportRequest a = (PlantReportRequest) plantTable.getValueAt(selectedRow, 0);
            a.setStatus("Handled");
            populatePlantTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_donePlantBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable animalTable;
    private javax.swing.JButton doneAnimalBtn;
    private javax.swing.JButton donePlantBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable plantTable;
    // End of variables declaration//GEN-END:variables
}
