/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.FieldTeam;

import Business.Species.AnimalSpecies;
import Interface.Employee.*;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import Interface.Administrator.AnimalPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YueZheng
 */
public class EmployeeAccountJPanel1 extends javax.swing.JPanel {

    private JPanel CardPanel;
    private UserAccount userAccount;
    
    /**
     * Creates new form EmployeeAccountJPanel
     */
    public EmployeeAccountJPanel1(JPanel a, UserAccount b) {
        initComponents();
        this.CardPanel=a;
        this.userAccount=b;
        userNameTXT.setText(userAccount.getUsername());
        populateEmergency();
        this.setBackground(null);
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameTXT = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        em = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("My Account ");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Group:");

        userNameTXT.setEditable(false);
        userNameTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTXTActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        em.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        em.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Location", "Emergency Type", "Status"
            }
        ));
        em.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(em);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Emergency Work Schedule");

        doneBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        doneBtn.setText("Done");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        backBtn1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        backBtn1.setText("Change Password");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160)
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(231, 231, 231)
                            .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void populateEmergency(){
        DefaultTableModel dtm = (DefaultTableModel) em.getModel();
        dtm.setRowCount(0);
        for (EmergencyRequest e: userAccount.getWorkQueue().getEmergencyRequest()) {
             Object[] row = new Object[4];
             row[0] = e; 
             row[1]=e.getDescription();
             row[2]=e.getMessage();
             row[3]=e.getStatus();
             dtm.addRow(row);         
        }
    } 
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);

    }//GEN-LAST:event_backBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = em.getSelectedRow();
        if (selectedRow >= 0) {
           EmergencyRequest a = (EmergencyRequest) em.getValueAt(selectedRow, 0);
           a.setStatus("Handled");
           populateEmergency();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        EmployeePasswordChange panel = new EmployeePasswordChange(CardPanel,userAccount);
        CardPanel.add("EmployeePasswordChange",panel);
        CardLayout layout = (CardLayout)CardPanel.getLayout();
        layout.next(CardPanel);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void userNameTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton doneBtn;
    private javax.swing.JTable em;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTextField userNameTXT;
    // End of variables declaration//GEN-END:variables
}
