/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.FieldTeam;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Interface.Employee.EmployeeAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class FieldTeamWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FieldTeamJPanel
     */
    private JPanel cardJPanel;
    private Enterprise enterprise;
    private UserAccount account;

    public FieldTeamWorkAreaJPanel(JPanel cardJPanel,UserAccount account, Enterprise enterprise) {
        initComponents();
        this.account = account;
        this.cardJPanel = cardJPanel;
        this.enterprise = enterprise;
        this.setBackground(null);
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkAlertBtn = new javax.swing.JButton();
        checkAlertBtn1 = new javax.swing.JButton();
        myAccountBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Field Team");

        checkAlertBtn.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        checkAlertBtn.setText("Alerts");
        checkAlertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAlertBtnActionPerformed(evt);
            }
        });

        checkAlertBtn1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        checkAlertBtn1.setText("Report Emergency");
        checkAlertBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAlertBtn1ActionPerformed(evt);
            }
        });

        myAccountBtn.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        myAccountBtn.setText("My Account");
        myAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkAlertBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkAlertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(checkAlertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(checkAlertBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(myAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myAccountBtnActionPerformed
        // TODO add your handling code here:
        EmployeeAccountJPanel1 eajp = new EmployeeAccountJPanel1(cardJPanel, account);
        cardJPanel.add("EmployeeAccountJPanel1", eajp);
        CardLayout layout = (CardLayout) cardJPanel.getLayout();
        layout.next(cardJPanel);

    }//GEN-LAST:event_myAccountBtnActionPerformed

    private void checkAlertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlertBtnActionPerformed
        // TODO add your handling code here:
        CheckAlertsJPanel eajp = new CheckAlertsJPanel(cardJPanel, enterprise, account);
        cardJPanel.add("CheckAlertsJPanel", eajp);
        CardLayout layout = (CardLayout) cardJPanel.getLayout();
        layout.next(cardJPanel);

    }//GEN-LAST:event_checkAlertBtnActionPerformed

    private void checkAlertBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlertBtn1ActionPerformed
        // TODO add your handling code here:
        ReportEmergencyJPanel eajp = new ReportEmergencyJPanel(cardJPanel, enterprise, account);
        cardJPanel.add("ReportWildFireJPanel", eajp);
        CardLayout layout = (CardLayout) cardJPanel.getLayout();
        layout.next(cardJPanel);

    }//GEN-LAST:event_checkAlertBtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAlertBtn;
    private javax.swing.JButton checkAlertBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton myAccountBtn;
    // End of variables declaration//GEN-END:variables
}
