/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee.FieldTeam;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author YueZheng
 */
public class ReportEmergencyJPanel extends javax.swing.JPanel {

    private JPanel cardJPanel;
    private Enterprise enterprise;
    private UserAccount account;

    /**
     * Creates new form ReportWildFireJPanel
     */
    public ReportEmergencyJPanel(JPanel cardJPanel, Enterprise enterprise, UserAccount account) {
        initComponents();
        this.account = account;
        this.cardJPanel = cardJPanel;
        this.enterprise = enterprise;
        this.setBackground(null);
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public boolean locationPatternCorrect() {
               String PATTERN ="((\\d|[1-9]\\d|1[0-7]\\d)°(\\d|[0-5]\\d)′(\\d|[0-5]\\d)(\\.\\d{1,6})?\\″(N|S))|(180°0′0\\″)";
               Pattern patt =Pattern.compile(PATTERN);
               Matcher m=patt.matcher(locationtxt.getText());
          
        boolean b =m.matches();
        if(b == false)
        {
            return false;
        } 
        return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        alertAdminBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        locationtxt = new javax.swing.JTextField();
        emergencytxt = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 24)); // NOI18N
        jLabel1.setText("Report Emergency");

        alertAdminBtn.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        alertAdminBtn.setText("Alert Admin");
        alertAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertAdminBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Al Bayan", 1, 15)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel2.setText("Location");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel3.setText("Emergency");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alertAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emergencytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emergencytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(alertAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cardJPanel.remove(this);
        CardLayout layout = (CardLayout) cardJPanel.getLayout();
        layout.previous(cardJPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alertAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertAdminBtnActionPerformed
        // TODO add your handling code here:
        if(locationtxt.getText()==null || emergencytxt.getText()==null || locationtxt.getText().equals("") || emergencytxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter all fields!");
            return;
        }
        String location = locationtxt.getText();
        String emergency = emergencytxt.getText();
        EmergencyRequest request = new EmergencyRequest();
        request.setDescription(location);
        request.setMessage(emergency);
        request.setSender(account);
        request.setStatus("Solving");
        enterprise.getWorkQueue().getEmergencyRequest().add(request);
        account.getWorkQueue().getEmergencyRequest().add(request);
        JOptionPane.showMessageDialog(null, "Successfully Alert");
        locationtxt.setText("");
        emergencytxt.setText("");
    }//GEN-LAST:event_alertAdminBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertAdminBtn;
    private javax.swing.JTextField emergencytxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField locationtxt;
    // End of variables declaration//GEN-END:variables
}
